### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by superacidjax** [wistia/wistia-uploader#4]
The documentation for using this as an actual ruby gem within a Rails project is pretty thin, perhaps it could be expanded to explain how to properly configure this in a rails project. For example, setting the API key/password from the command line is pretty clear, but there's no context in terms of a rails application. Should the API password be an environment variable, for example in an initializer or something else. It's a good "Command line" client, however the Wistia docs are promoting this as an "easy" way to upload from a rails application. It's not easy if the configuration docs don't even mention rails.

**Comment by freerobby** [comment]
@superacidjax Thanks for reporting this. Sadly, we goofed on our docs and lead you astray. The wistia-uploader gem is intended to be used as a command line tool for uploading videos from your terminal, not as a Ruby library in third party applications. The upload API doc does have a [functional example](http://wistia.com/doc/upload-api#example_code), which I'd recommend perusing if you want to hit our API via Ruby, but I wouldn't recommend using the wistia-uploader gem. Sorry about this; we will update our docs to clarify this for others.

**Comment by superacidjax** [comment]
no problem, I am in the midst of my never ending path towards Clarity. Thanks. It completely makes sense as a command liner, obviously. Just wanted to be sure I wasn't suffering from brain damage based on my inability to integrate this with a rails app.

**Comment by freerobby** [comment]
@superacidjax Nope - you're not missing anything, and thanks again for bringing it to our attention.

@jeffvincent I pushed a [change](https://github.com/wistia/wistia-doc/pull/14) for this but it didn't seem to update the live pages. Any thoughts on why that might be?

**Comment by jeffvincent** [comment]
@freerobby there might be something wonky going on with the `jekyll` service on the docbox. I just tried nuclear_updating and the change took effect. Service is going directly to `crashed` state - will need to look into that further :camel:

**Comment by freerobby** [comment]
@jeffvincent Thanks! I'm going to close this issue since this in particular is now resolved.
